resilience4j.circuitbreaker:
  backends:
    drinkApp:
      ringBufferSizeInClosedState: 6
      ringBufferSizeInHalfOpenState: 3
      waitInterval: 5000
      failureRateThreshold: 50
      eventConsumerBufferSize: 20
